# .streamlit/secrets.toml

[hopsworks]
project = "sneha_taxi_project"
api_key = "tMxCpQUhLIu3cF4M.MvcKqmKXfvYzHBeLz15mgRmViawD3LkZNefu9mFHYMQRyu6udS1tVMEldG5aJYpA"

[mlflow]
username = "sai-snehitha"
password = "e3233f7dafa1eca6b73e8aff9239b1c31de90620"
tracking_uri = "https://dagshub.com/sai-snehitha/citi-bike-prediction-system.mlflow"
